* Dockerfile for Inadyn
  A Dockerfile to run [[https://github.com/troglobit/inadyn][troglobit/inadyn]], a DDNS client.

** Example usage
   The example below shows how to set up the container using docker compose.

   Before proceeding, make sure that the docker compose command is executable.
   #+begin_src bash
     docker compose version
   #+end_src

   Expected ouput is something like this:
   #+begin_example
     Docker Compose version v2.6.1
   #+end_example

   Create a directory to store a configuration file.
   #+begin_src bash
     mkdir -p ~/inadyn/data
   #+end_src

   Create a docker compose configuration file as follows, or you can copy it from [[file:compose.yaml][here]].
   By default, inadyn in this container reads =/data/inadyn.conf= as a configuration file.
   #+begin_src bash
     cat <<EOF >~/inadyn/compose.yaml
     services:
       inadyn:
         image: mocknen/inadyn
         container_name: inadyn
         restart: unless-stopped
         volumes:
           - type: bind
             source: data
             target: /data
             read_only: true
           - type: volume
             source: cache
             target: /home/nonroot/.cache/inadyn
     volumes:
       cache:
     EOF
   #+end_src

   Create an inadyn configuration file.
   #+begin_src bash
     cloudflare_zone=example.com
     cloudflare_api=XYZabcdefghijklmnopqrstuvwxyz0123456789A
     target_name=usage.example.com
     cat <<EOF >~/inadyn/data/inadyn.conf
     period = 600

     provider default@cloudflare.com {
         username = ${cloudflare_zone}
         password = ${cloudflare_api}
         hostname = ${target_name}
         checkip-server = api.ipify.org
     }
     EOF
   #+end_src

   Optionally, make sure there are no problems with the configuration file.
   No output means no problem.
   #+begin_src bash
     docker compose -f ~/inadyn/compose.yaml run --rm inadyn --check-config
   #+end_src

   Fire up!
   #+begin_src bash
     docker compose -f ~/inadyn/compose.yaml up -d
   #+end_src

   Check the log.
   #+begin_src bash
     docker compose -f ~/inadyn/compose.yaml logs -t
   #+end_src

   Shut down.
   #+begin_src bash
     docker compose -f ~/inadyn/compose.yaml down
   #+end_src

   If you encounter problems, you can run it with debug information displayed.
   #+begin_src bash
     docker compose -f ~/inadyn/compose.yaml run --rm inadyn --foreground --no-pidfile --loglevel=debug
   #+end_src
